### ISSUE TITLE
Cannot find the data under Python

### ISSUE THREAD

**Issue by mzhang001** [BayesianTestsML/tutorial#2]
I am trying to run the python codes, and the program cannot find any data for further analysis. 

I wonder where to download them or how to generate them?

**Comment by janezd** [comment]
What did you try to run and how?

**Comment by mzhang001** [comment]
I executed the notebooks in tutorial/Python/

The problem is tutorial/Python/data contains nothing, which should contain the predictions for different models.

**Comment by 7rabbit** [comment]
Dear Project owner,

I have a similar problem. I try to run /hierarchical/analyze_uci_with_rope.R. The code at line 23 gives an error because "uci_data.RData" cannot be found. This problem is similar to the issue discussed here except it is related to R. 

Thank you for your time including the data sets.
Regards

**Comment by bjornragu** [comment]
Dear,

I'm going through the python codes and I have the same problem as stated here above. The data file (with the predicted accuracy of the two classifiers) seems to be empty.

Kind regards

**Comment by daminier** [comment]
Try to generate them or using another dataset! I did it and it's not difficult at all! The notebooks are really well commented so you wouldn't have problems understanding what you need as input (you have to change just that!).
